language: node
sudo: false

before_install:
  - nvm install $(cat .nvmrc)
  - nvm use
  - npm i -g npm
  - npm i -g firebase-tools

script:
  - echo "No build required"

deploy:
  - provider: script
    script: bash -c "npx firebase deploy --only hosting"
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master)$
